import Joi from 'joi';
import ConfigKey from './config-key';

export default Joi.object({
    [ConfigKey.PORT]: Joi.number().default(3000),
    [ConfigKey.VERSION]: Joi.string().required(),
    [ConfigKey.BASE_PATH]: Joi.string().required(),
    [ConfigKey.CORS_WHITELIST]: Joi.string().required(),
    [ConfigKey.LOG_LEVEL]: Joi.string()
        .valid('error', 'warn', 'info', 'http', 'verbose', 'debug', 'silly')
        .required(),
    [ConfigKey.JWT_ACCESS_TOKEN_EXPIRED_IN]: Joi.number().required(),
    [ConfigKey.JWT_ACCESS_TOKEN_SECRET_KEY]: Joi.string().required(),
    [ConfigKey.JWT_REFRESH_TOKEN_EXPIRED_IN]: Joi.number().required(),
    [ConfigKey.JWT_REFRESH_TOKEN_SECRET_KEY]: Joi.string().required(),
    [ConfigKey.MONGO_DATABSE_CONNECTION_STRING]: Joi.string().required(),
    [ConfigKey.MONGO_DEBUG]: Joi.string().valid('enable', 'disable'),
    [ConfigKey.SENDGRID_API_KEY]: Joi.string().required(),
    [ConfigKey.SENDGRID_SENDER]: Joi.string().required(),
    [ConfigKey.SENDGRID_TEMPLATE_ID_CONTACT_USER]: Joi.string().required(),
    [ConfigKey.SENDGRID_TEMPLATE_ID_NEW_PASSWORD]: Joi.string().required(),
    [ConfigKey.SENDGRID_TEMPLATE_ID_RESET_PASSWORD]: Joi.string().required(),
    [ConfigKey.SENDGRID_TEMPLATE_ID_NEW_PASSWORD_WITH_ACTIVATION_LINK]:
        Joi.string().required(),
    [ConfigKey.SENDGRID_TEMPLATE_ID_SEND_SUPPORT_REQUEST]:
        Joi.string().required(),
    [ConfigKey.SENDGRID_SUPPORT_REQUEST_ADMIN]: Joi.string().required(),
    [ConfigKey.SENDGRID_TEMPLATE_ID_ACCOUNT_CREATED_INFORM]:
        Joi.string().required(),
    [ConfigKey.WEB_APP_BASE_URL]: Joi.string().required(),
    [ConfigKey.WEBVIEWER3D_BACKEND_WEBSOCKET_URL]: Joi.string().required(),
    [ConfigKey.WEBVIEWER3D_PASSPHRASE]: Joi.string().required(),
    [ConfigKey.WEBVIEWER3D_MODEL_REPOSITORY]: Joi.string().required(),
    [ConfigKey.WEBVIEWER3D_MODEL_EXPORT_REPOSITORY]: Joi.string().required(),
    [ConfigKey.SFTP_HOST]: Joi.string().required(),
    [ConfigKey.SFTP_PORT]: Joi.string().required(),
    [ConfigKey.SFTP_USERNAME]: Joi.string().required(),
    [ConfigKey.SFTP_PASSWORD]: Joi.string().required(),
    [ConfigKey.SFTP_PROJECT_DEFAULT_PATH]: Joi.string().required(),
    [ConfigKey.SFTP_USERS_DEFAULT_PATH]: Joi.string().required(),
    [ConfigKey.SFTP_TEMP_FOLDER]: Joi.string().required(),
    [ConfigKey.SFTP_TEMP_DOWNLOAD_FOLDER]: Joi.string().required(),
    [ConfigKey.SSH_HOST]: Joi.string().required(),
    [ConfigKey.SSH_PORT]: Joi.string().required(),
    [ConfigKey.SSH_USERNAME]: Joi.string().required(),
    [ConfigKey.SSH_PRIVATE_KEY_PATH]: Joi.string().required(),
    [ConfigKey.THUMBNAIL_FOLDER]: Joi.string().required(),
    [ConfigKey.BACKEND_API_URL]: Joi.string().required(),
    [ConfigKey.FILE_STORAGE_SUPPORT_REQUEST_FOLDER]: Joi.string().required(),
    [ConfigKey.FILE_STORAGE_SUPPORT_REQUEST_PATH]: Joi.string().required(),
    [ConfigKey.FILE_STORAGE_BASE_URL]: Joi.string().required(),
    [ConfigKey.FILE_STORAGE_SUPPORT_REQUEST_CSV_FOLDER]:
        Joi.string().required(),
    [ConfigKey.FILE_STORAGE_SUPPORT_REQUEST_CSV_PATH]: Joi.string().required(),
    [ConfigKey.FILE_STORAGE_THUMBNAIL_PATH]: Joi.string().required(),
    [ConfigKey.FILE_STORAGE_DOWNLOAD_PATH]: Joi.string().required(),
    [ConfigKey.CRON_JOB_DOWNLOAD_INSTANCE_LOG]: Joi.string().required(),
    [ConfigKey.CRON_JOB_DOWNLOAD_SERVER_LOG]: Joi.string().required(),
    [ConfigKey.CRON_JOB_DOWNLOAD_LICENSE_LOG]: Joi.string().required(),
    [ConfigKey.SFTP_INSTANCE_LOG_FOLDER_PATH]: Joi.string().required(),
    [ConfigKey.SFTP_SERVER_LOG_FOLDER_PATH]: Joi.string().required(),
    [ConfigKey.SFTP_LICENSE_LOG_FOLDER_PATH]: Joi.string().required(),
    [ConfigKey.REDIS_HOST]: Joi.string().required(),
    [ConfigKey.REDIS_PORT]: Joi.string().required(),
    [ConfigKey.REDIS_PASSWORD]: Joi.string().required(),
    [ConfigKey.FILE_STORAGE_PLANNING_FOLDER]: Joi.string().required(),
    [ConfigKey.FILE_STORAGE_PLANNING_PATH]: Joi.string().required(),
});
